# use

use( Promise | Context )  
Хук, который позволяет зачитывать значения из Promise и Context  
В отличие от других хуков, use() может быть вызван внутри циклов и if{} else{}  
конструкций. Однако не может быть помещён внутри блока try catch  

## Использование с Promise

Если в дочернем компоненте используется хук use, в который передаётся Promise  
use(Promise), то в родительском компоненте целесообразно обёрнуть дочерний  
компонент в suspense и errorBoundary  

Пока дочернем компоненте Promise будет резолвится, в родительском компоненте  
будет показан fallback от suspense. После того как в дочернем компоненте  
promise зарезолвится, fallback будет заменён на рендер дочернего компонента  
вместе с результатом зарезолвившегося promise  

В случае, если promise будет rejected, сработает fallback от errorBoundary.  
Вместо errorBoundary при реджекте promise можно использовать .catch(() => {})  
синтаксис и тогда будет отображёт его результат.  

Нужно иметь в виду что хук use() не может быть вызван внутри блока try{} catch  
Вместо этого следует использовать один из вариантов выше  

## Использование с Context

При передаче в use Context данный хук работает аналогично хуку useContext  
за исключением того, что хук use может быть вызван внутри циклов и условий  

useContext(context) === use(context)  
